### PR TITLE
Build images for arm v7 and arm64

### PR DESCRIPTION
**Pull request by jwkicklighter**
This is untested because I'm not sure the best way to run the action on my own fork, but after reading #647 and investigating `package.json`, `Dockerfile`, the relevant entrypoint file, and the action workflow, I believe that specifying the platforms here may be all that is left to have ARM builds.

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Hi, could this be changed over to the development branch please? 

The nodejs 15 check will pass then.

Thanks for looking into this though! The only one I'm not so sure about is the monolithic but they'll be able to build on the development tag to be tested.

**Comment by NotExpectedYet** [comment]
> This is untested because I'm not sure the best way to run the action on my own fork, but after reading #647 and investigating `package.json`, `Dockerfile`, the relevant entrypoint file, and the action workflow, I believe that specifying the platforms here may be all that is left to have ARM builds.


Success! Realized it didn't matter about mongodb. 

Big thanks again!

image

**Comment by jwkicklighter** [comment]
@NotExpectedYet thanks for getting that onto the right branch! I actually looked at the branch structure before I forked, but apparently I wasn't awake enough when I made the PR. Glad to see the build go through, hopefully there are no surprises!

**Comment by NotExpectedYet** [comment]
@jwkicklighter 

Gives us some breathing room been on development at least. I'll make sure to give them a check out but should be no issues. Thanks again!

**Pull request merged**
