### PR TITLE
🙏🏼 release 1.2 - performance improvements, bugfixes and quality of life

### PR DESCRIPTION
**Pull request by davidzwa**
_RELEASE CANDIDATE - UPDATE WITH CARE AND DONT RUSH IT_

# Release candidate 1 for version 1.2
Long awaited release candidate named `1.2-rc1` where we introduce a lot of bugfixes for printer management, code cleanup and optimization for Windows OS based installs where SystemInformation (CPU, RAM, disk) would massively slow down the OctoFarm server. Secondly we introduce a **version 2.x NestJS server and VueJS client prototypes** to show you we are not standing still here at OctoFarm. Furthermore I've cleaned up a lot of the code in the server to be able to port it to version 1.2.x and 2.x future releases. Finally I've written a lot of unit, integrations and API tests using `jest` and `mongodb-memory-server` which have already worked a treat in catching bugs in the PR's which came after!
James gave printer management and the settings panels a massive robustness boost with a lot more stability to be expected, although .... its not expected yet padumtssssssssssss. Happy Printing!

David and James

## Pull-requests
- PR #631 Windows/Linux OctoFarm server speedup (x5/x10 performance improvement due to SystemInfo being atrociously slow)
- PR #545 printer settings management is now passing the right serial connection data to OctoPrint 
  - Save notifications: 1 save confirmation message combined instead of 3 separate saving messages
  - Server calls: removed a lot of redundant OctoPrint API calls, speeding up the save response by 2x/3x
  - Failure robustness: errors wont break the settings dialog anymore
  - Added back Offline checks to prevent OctoPrint connection errors for fetching or updating settings
  - #531 #562 port preference option now used to check if the printer is Offline/Disconnected
  - #532 printer settings dialog now grabs fresh data from OctoPrint - it didnt do this correctly before
- PR #597 added OctoPrint API compatibility checks and new call to OctoPrint API 1.6.0 for plugin manager
  - Fixed small bug in the main state `Runner` w.r.t. `settingsAppearance` not being properly checked for being undefined
- PR #575 separated and optimized the client for the OctoPrint API to get it out of main state `Runner`
- PR #585 added ability to choose HTTPS separately from WSS for websockets
  - Follow-up PR #610 #611 printer bulk update buttons for system and plugin updates now show up again
  - Follow-up PR #614 `Offline after Error` state now correctly processed as erroneous printer state (Red instead of Yellow)
  - Follow-up PR #616 Fix the slight mishaps from #585 up until #614
- PR #570 Node 12/13 (<14) abort page failed due to Node 14+ syntax
  - #546 Node 12/13 abort page added and fixed to actually work for Node12. Added docker node 12 test Dockerfile
- PR #406 History Analysis cache refactored 
  - #576 hotfix of History Analysis - `ReferenceError: Cannot access 'checkNested' before initialization`
  - #577 hotfix of History Analysis - `sumValuesByGroup undefined`
  - #381 Found and removed 1 out of 2 circular imports
  - PR #568 New OctoFarm databases doesnt crash anymore with `PrinterClean x of undefined` by preventing a heatMap database initialization race condition in `printerClean.js`
- PR #601 API testing and users/registration route init optimization
- PR #426 File Analysis refactored  
- PR #419 Job Analysis refactored  
- PR #580 Remove ensureIndex warning, update mongodb-driver mongoose and avoid circular import of the main state `Runner`
  - #542 Modules `filamentManagerPlugin` is now imported the Runner, but dont import Runner themselves anymore
  - #381 Second non-problematic circular dependency errors in logs have been found and prevented 
- PR #505 Version 1.2.x/2.x NestJS server is now merged and we will keep it compatible and up-to-date with version 1.x releases
  - PR #561 version 2 server now has a History Analysis service and cache
  - PR #619 version 2 server now has a Job Statistics Analysis service and cache
  - PR #623 version 2 server now has a File Statistics Analysis service and cache
- PR #560 VueJS version 2.x client prototype introduced
  - PR #571 VueJS client migrated to Typescript
- PR #556 #564 updates of used NPM package dependencies like pkg and gulp
- PR #583 massive code cleanup by running Prettier with `"prettier --write \"./server_src/**/*.js\" \"./test/**/*.js\""`
- PR #557 Patreons synced with last state

## Issues and improvements to be resolved for 1.2-rc2
- #605 having no spool selected shows `null` instead of `No Spool`
- #606 Expected units total is displaying 0 with spool selected
- #607 Allow Current User to be saved in database / Editable in UI
- #615 Refactor the printer settings saving flow
- #617 Resyncing printer shows "Shutdown" shortly
- #618 Root cause not yet found/fixed (file property exception of job which is incorrectly null)
- #624 MongoDB Error saving farmPrinter in trackCounters after printer creation
- #625 Template printer management wrong closing/opening of tags
- #548 printer management table is not looking to good (wrapping)
- #538 Filament / History Graphs stay "loading..." when no data presented if outside 30 day window
- #536 Client is too slow to respond to server restart, iAmAlive check comes back too quick
- #388 Completely Depricate Wiki and move over to website (or whats left of it)
- #374 Couple server port to .env and ditch serverSettings prop
- #366 history.js file and cleanup

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Question... @davidzwa I thought we we're doing RC's from development? Due to new users getting rc branches with the current instructions?

**Comment by davidzwa** [comment]
> Question... @davidzwa I thought we we're doing RC's from development? Due to new users getting rc branches with the current instructions?

We could implement the tag based pull instead. Sound good?

**Comment by NotExpectedYet** [comment]
> > Question... @davidzwa I thought we we're doing RC's from development? Due to new users getting rc branches with the current instructions?
> 
> We could implement the tag based pull instead. Sound good?

We could but I need to update OF first

**Comment by davidzwa** [comment]
Ill leave this PR open as a final release PR for 1.2 then.

**Comment by NotExpectedYet** [comment]
Shall we get the settings and webpack stuff done and do an RC? Gives us a pretty clean break for the other feature work and additions we wanna do. 

It's getting a pain to keep merging my settings work in I'll be honest. Dunno how you keep doing it 😂.

**Comment by davidzwa** [comment]
Tbh gitkraken is doing all the heavy lifting for me. I would go crazy without. 

Settings can certainly go in when its done and fully tested.

**Comment by NotExpectedYet** [comment]
@davidzwa aye deffo. Oh I was meaning keeping my changes like. Settings touches a lot so it's a lot to re-apply depending where the other PRs touch. I haven't really played with merging in gitkraken, I should, if it does.  

Right so I have 

- [ ] update the documentation on the website to use release tags. 
So: `git clone git@github.com:octofarm/octofarm.git --branch 1.1.13-hotfix`
- [ ] merge webpack
- [ ] rc1

**Comment by davidzwa** [comment]
Shouldn't it be - - tag?

**Comment by davidzwa** [comment]
> @davidzwa aye deffo. Oh I was meaning keeping my changes like. Settings touches a lot so it's a lot to re-apply depending where the other PRs touch. I haven't really played with merging in gitkraken, I should, if it does.

@tideline3d I hope you can word what I am about to say as I believe you're a good point of reference.  @NotExpectedYet the next stuff is better to discuss in a call, but I'll share directly anyway :)

## Terminal vs UI
Things we cant do easily or quickly in terminal/WebStorm/VS Code:
- **stage/ unstage** - see what I have changed before committing, filter it out changes
- **auto stashing** - GitKraken can stash uncommitted changes to make sure nothing is lost when a failure occurs
- **what is out there** seeing remote commits before pulling them... admit it this is sick
- **history** see my previous commits
- **resetting on future/history** squashing (soft reset: needs a specific commit hash, finick commands to type)
- **rebasing conflicts** rebase with merge conflicts resolution (quite some repetition of steps, lot of commands to type)
- **merge conflicts** merge with a visual merging tool (manual merge... yuck! 🤮)
- **commits** stage and commit rapidly with message `git stage ....`, `git add ...` `git commit -m "asdasdasdasd"`, `git push`
- **problematic files** merge conflicts for moved, renamed or removed files 
- **newly ignored files** gitignore and untrack/purge from remote repository
- **pull other branches** pull another branch to itself (good luck doing that in terminal with 1 command)
https://stackoverflow.com/questions/18857570/git-pull-without-checkout
- **checkout remotely force pushed branch** hard reset to pull a rebased branch without conflicts (git reset --hard .... commit hash??? => undoable)

You see why I would really like my fellow developers to switch? I want them to be efficient and have confidence in their version control workflow, so I can have confidence that what they publish to PR's is upholding the quality standards we agreed upon beforehand. 
Btw, this could have major impact on how other developers see OctoFarm: is the repo inviting to contribute to or is it a jungle? Is the code aligning conventional naming or does it require a big study beforehand? Missing `CONTRIBUTING.MD` has impact as well I believe.

## Common git workflow, coding style and coding principles

Using the same tools, coding style and workflow is not a special thing: set up an workflow agreement written down in f.e. markdown and avoid deviating from that. When a colleague/developer doesnt understand the tool chosen he needs to either learn it or get help and practice until he's fluent in the workflow. 
Changes to this ruleset is only possible through discussion and amendments.
My point is that we've got this covered 80% already by working together for months. The last 20% percent is:
- git tool to use (GitKraken, SourceTree, Github Desktop, etc) => no terminal unless it cant be avoided
- pull-request criteria (backend, frontend and e2e tests. Changelog. PR description. PR labels/milestone/project/issue)
- issue or discussion?
- project or milestone?
- squashing + rebase or merging
- templating release notes
- versioning and release flow
- code style and (prettier is nice, but not enforced by linting)
- code principles (principles: SRP single-responsibility principle, DRY dont-repeat-yourself... you tend to repeat your code a lot still and Im not sure if its because you dont notice or because you want to be quick. Im quite intolerant to it as the fix/cleanup is faster than the impact of badly written code)

When these things are in order... it can truly elevate your efficiency and joy in coding/collaborating

**Comment by NotExpectedYet** [comment]
@davidzwa it's honestly easier for me to digest like this. Sorry I never mentioned the call my cousin turned up that night. I'm currently digesting and will give my thoughts. The majority looks good and it's just a formality to what we've discussed before anyway.

**Pull request closed without merging**
