### PR TITLE
Update to latest minor version of Node and Alpine

### PR DESCRIPTION
**Pull request by davidzwa**
Stay on top.

### CODE REVIEW

**Comment by davidzwa** [comment]
Yuck, it seems `jest` is throwing a tantrum when `npm install --only=production` is being called. Yuck yuck yuck.

**Comment by NotExpectedYet** [comment]
> Yuck, it seems `jest` is throwing a tantrum when `npm install --only=production` is being called. Yuck yuck yuck. Prolly have to check the lock file

The logs are saying it's pkg in the docker alpine one as well, dunno if you saw.

**Comment by davidzwa** [comment]
> > Yuck, it seems `jest` is throwing a tantrum when `npm install --only=production` is being called. Yuck yuck yuck. Prolly have to check the lock file
> 
> The logs are saying it's pkg in the docker alpine one as well, dunno if you saw.

Good call, lets remove pkg. Its not a thing which should constrain our PROD containers... ffs

**Comment by NotExpectedYet** [comment]
> > > Yuck, it seems `jest` is throwing a tantrum when `npm install --only=production` is being called. Yuck yuck yuck. Prolly have to check the lock file
> > 
> > 
> > The logs are saying it's pkg in the docker alpine one as well, dunno if you saw.
> 
> Good call, lets remove pkg. Its not a thing which should constrain our PROD containers... ffs

Move it to a dev dependency? It's not been used at the moment either way like so removal is fine for me.

**Comment by davidzwa** [comment]
Its already dev

**Comment by davidzwa** [comment]
@NotExpectedYet build seems fixed with pkg removal. I removed the package json script and config as well

**Review by NotExpectedYet — APPROVED** [review]

**Pull request merged**
