### PR TITLE
Bugfix/sse flatted new major version namespace

### PR DESCRIPTION
**Pull request by davidzwa**
The `flatted/cjs` endpoint had to be changed to `flatted` for version 3 of this package.

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Worth updating the client too? It uses my parsed file as I could never import it from node_modules before.

**Comment by davidzwa** [comment]
Ah righto, yeah sounds good

**Comment by davidzwa** [comment]
@NotExpectedYet shall we merge this? The client side I dont have the time for.
Repercussion: SSE will fail when V2 flatted is installed instead of V3. Write a fallback?
Alternative: revert

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet shall we merge this? The client side I dont have the time for.
> Repercussion: SSE will fail when V2 flatted is installed instead of V3. Write a fallback?
> Alternative: revert

sorted client, just waiting for checks to run

**Review by NotExpectedYet — APPROVED** [review]

**Pull request merged**
