### PR TITLE
fix incorrect ws url fix (#731)

### PR DESCRIPTION
**Pull request by NotExpectedYet**
#731 - This was a mistake on my part from switching to the big one branch.

### CODE REVIEW

**Comment by davidzwa** [comment]
Should we aim to use the new URL(..).href approach? Curious what your thoughts on it are, I think its kinda neat

**Review by davidzwa — CHANGES_REQUESTED** [review]
Sorry, I think we can do better to fix either slash or not

**Comment by NotExpectedYet** [comment]
> Sorry, I think we can do better to fix either slash or not

I'm not saying we can't, I wanted to get development fixed and just revert my previous changes as they we're made in error.

**Review by davidzwa — APPROVED** [review]
mb mb :)

**Pull request merged**
