### PR TITLE
Add github release check

### PR DESCRIPTION
**Pull request by davidzwa**
- [x] Check github at startup + save state
- [x] Dont await request (non-essential to server start)
- [x] Avoid doing check for air-gapped farms (using google.com)
- [x] Push to amialive
- [x] Add UI alert to perform update
- [x] Add mark read and update button to notification
- [x] Add very short and nonintrusive reminder notification (reminder fallback)
- [x] Use logger instead of console.log
- [x] Write below regression tests
- [x] Detect whether within pm2, nodemon or docker environment and adjust feedback accordingly.
- [ ] Couple to update commands + restart with pm2

Tests
- [x] Add npm_package_version undefined test
- [x] Add mocked Github response test (to regression test tag_name)
- [x] Test air-gapped (mock + docker + IRL)
- [x] (Optional) test erroneous state

Impact on rapid-restarts? Timeout maybe?

### CODE REVIEW

**Comment by davidzwa** [comment]
@NotExpectedYet I do wonder whether I should await this request to github (how to deal with air-gapped farms).

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet I do wonder whether I should await this request to github (how to deal with air-gapped farms).

I totally agree there. If it fails then the server shouldn't hang. If the client checks and no update is available continue on as normal. 

Maybe check for connectivity first? Then the client will just get null back or whatever you prefer.

**Comment by davidzwa** [comment]
Faked version and faked disconnected (simple boolean toggle after google fetch):
image

Faked version (left connection intact):
image

**Comment by davidzwa** [comment]
image
Current endpoint output

**Comment by NotExpectedYet** [comment]
You seem to be missing a changelog addition

**Review by NotExpectedYet — COMMENTED** [review]
Looks fine to merge to me man nice work. 

Merge and then I can use this as a base for the new server command to run the update

**Review by NotExpectedYet — DISMISSED** [review]

**Comment by NotExpectedYet** [comment]
Oh wait, needs those other changes you mentioned last night.

**Comment by davidzwa** [comment]
> Oh wait, needs those other changes you mentioned last night.

We can do this with a follow-up PR and 5 extra pushups on my side.

**Comment by davidzwa** [comment]
> You seem to be missing a changelog addition

I added it good point!

**Comment by NotExpectedYet** [comment]
> > You seem to be missing a changelog addition
> 
> I added it good point! @NotExpectedYet you can merge it after you approve

No trouble man :)

**Review by NotExpectedYet — APPROVED** [review]
Sweet as :D

**Pull request merged**
