### PR TITLE
Fix pm2 logging folder and service-worker missing in ecosystem

### PR DESCRIPTION
**Pull request by davidzwa**
Fixes:
- [x] remove logs folder + file quotes for pm2 (npm start)
- [x] tested on win10
- [x] small cleanup ecosystem.config.js `./service-worker` specification 
- [ ] regression tested on docker containers

### CODE REVIEW

**Review by NotExpectedYet — APPROVED** [review]
Seems fine, can test docker shortly

**Comment by NotExpectedYet** [comment]
One thing though, can you add any changes to the CHANGELOG.md file please?

**Comment by davidzwa** [comment]
Sure, I presume more instructions on Windows/Unix NodeJS or Docker?

**Comment by NotExpectedYet** [comment]
> Sure, I presume more instructions on Windows/Unix NodeJS or Docker?

Actual instructions for this. I'm still curious if it's because npm starting pm2.

**Pull request merged**
