### PR TITLE
Set node_env with production as default

### PR DESCRIPTION
**Pull request by davidzwa**
- [x] Ensure NODE_ENV is set to production by defaujlt
- [x] Adjust client_src package to new build, push build to NPM and use in server package.json
- [x] Adjust server package.json version to `1.2.0-rc1`
- [x] Changelog

### CODE REVIEW

**Comment by davidzwa** [comment]
@NotExpectedYet any idea why https://github.com/OctoFarm/OctoFarm/issues/659 is happening on this branch?

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet any idea why #659 is happening on this branch?

Hu, the styles not getting replaced on that card. Should be though I'd fixed it on the dashboard rework before commiting. 

Will take a look.

**Comment by davidzwa** [comment]
I think it is related to me tinkering on NODE_ENV or the logger, although I have no clue why the logger would influence frontend styling

**Comment by NotExpectedYet** [comment]
> I think it is related to me tinkering on NODE_ENV or the logger, although I have no clue why the logger would influence frontend styling

Yeah that's weird, the JS is running otherwise there would be no items and it removes the loader styles as soon as it puts the first item in. Unless I goofed something? or is it just that branch and not development.

**Comment by davidzwa** [comment]
Not dev, switched back and restarted webpack to be sure. All good again

**Review by NotExpectedYet — APPROVED** [review]

**Pull request merged**
