### PR TITLE
Chore/package updates

### PR DESCRIPTION
**Pull request by davidzwa**
{edit] Ready for merge. Should be harmless, but we should test.

### CODE REVIEW

**Review by NotExpectedYet — APPROVED** [review]
These are fine, and had no impact that I could tell. They're mainly dev dependencies anyway apart from .env.

**Comment by davidzwa** [comment]
I will test this later again as well, gotta check gulp etc

**Comment by NotExpectedYet** [comment]
> 
> 
> I will test this later again as well, gotta check gulp etc

It built fine for me like but no drama.

**Comment by davidzwa** [comment]
@NotExpectedYet postcss wasnt installed for me as it was a peer-dep for gulp-postcss... pretty weird must be a bug on their side (I guess windows only or maybe a transient installation problem)

**Comment by NotExpectedYet** [comment]
> 
> 
> @NotExpectedYet postcss wasnt installed for me as it was a peer-dep for gulp-postcss... pretty weird must be a bug on their side (I guess windows only or maybe a transient installation problem)

I tested on Windows but gather was already in my node_modules as I hadn't cleared before. Yeah weird one but good catch.

**Pull request merged**
