### PR TITLE
Fixed #500 - issues with auto connection on baudrate.

### LINKED ISSUE #500: Issue connecting to printers via OctoFarm interface (baudrate, serial port)
### Versions

* Your **OctoFarm version** (latest 1.1.13): 1.1.13 (I think...  LoL)
* Your **OctoPrint version** (latest 1.5.3): 1.5.3
* Docker or pm2: pm2
* **NodeJS version** 14 or 15 (not for docker): 14
* Operating System (f.e. Raspberry Pi OS, Ubuntu, Windows): Ubuntu
* OctoPrint Plugins (e.g. bed visualiser, octoklipper, printtimegenius): 

### Reproduction

* Description of the problem:
1 - When setting Preferred Baudrate in OctoFarm, it doesn't always save
2 - When Preferred Baudrate is not set, OctoFarm is unable to initiate a connect to the printer.  OctoPrint is set to AUTO and when connect is initiated from OctoPrint, it connects.

### OctoFarm Logs

Will provide logs at a later time.  Just wanted to get this logged per s1mpleman's request.  :-)

### PR DESCRIPTION
**Pull request by NotExpectedYet**
Added options to use the '0' value for baudrate. 

Updated client to change this to "AUTO" in text fields. 

Updated auto connect to fall back to using '0' not "AUTO"

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Client will need compiling to test this as I chose the development mins when merged

**Comment by davidzwa** [comment]
image
image

It no work no

**Review by davidzwa — CHANGES_REQUESTED** [review]
Bugs present. Better to fix now than later as these are vital for usage of OF's most basic functionality.

**Comment by NotExpectedYet** [comment]
Hmm I'll check that when I get back.

**Comment by NotExpectedYet** [comment]
I wonder if you can update the baud to a 0 over API. I'll test and find out though. 

The main thing here is on a resync it picks these settings up and allows them to be used on connection.

**Comment by davidzwa** [comment]
So just for administration, just checked. State.js has an update settings function which calls fetch to update settings.
- this does not contain port or baudrate
- update is skipped when printer is not connected. Dont understand why

**Comment by NotExpectedYet** [comment]
@davidzwa I'll add them. Probably forgot aha. 

Hu? It's when it's offline not disconnected. Can't update octoprint if it isn't there to be updated.

**Comment by davidzwa** [comment]
Ah ok read it too quick then

**Comment by NotExpectedYet** [comment]
Easily done xD

**Comment by davidzwa** [comment]
Changelog pls!

**Review by davidzwa — APPROVED** [review]

**Pull request merged**
